apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  node.name: "es01"
  cluster.name: "es-docker-cluster"
  discovery.type: "single-node"
  bootstrap.memory_lock: "true"
  xpack.security.enabled: "false"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  elastic_url: 'http://10.43.89.215:9200'  #elasticsearch-service