apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: elasticsearch-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: es-data-volume
          emptyDir: {}

          
---
#service 
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9200   
      targetPort: 9200
      #nodePort: 30000   
