#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: abtinz/film_recommender:v13
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8000
        env:
        - name: redis-URL       
          valueFrom:
            configMapKeyRef: 
              name: redis-config
              key: redis-url
        - name: elastic_URL
          valueFrom: 
            configMapKeyRef: 
              name: elasticsearch-config
              key: elastic_url



---
#service 
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100